name: Informações Confidenciais 2
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: MASCARA
        run: echo "::add-mask::${{ secrets.MY_SECRET_TOKEN }}"
      - name: TOKEN
        run: echo "your secret token is ${{ secrets.MY_SECRET_TOKEN }}"
