name: Informaçãoes Confidenciais
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Adiciona Mascara
        run: echo "::add-mask::${{ Chave }}"
      - name: Echo a secret  
        run: echo "Minha Senha screta é ${{ asd1a8a4484af188sd4f }}"
