name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.MINHA_SENHA_SECRETA }}"
      - name: Echo a secret  
        run: echo "Minha Senha é 1da5s1d5a81a88 ${{ secrets.MINHA_SENHA_SECRETA }}"
