name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Mascara
        run: echo "::add-mask::${{ secrets.MY_SECRET_TOKEN }}"
      - name: Senha-Token
        run: echo "your secret token is ${{ secrets.MY_SECRET_TOKEN }}"
